backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "معرض المشاريع"
    files:
      - label: "قاعدة بيانات المشاريع"
        name: "all_projects"
        file: "projects-1.json"
        fields:
          - label: "قائمة المشاريع"
            name: "projects"
            widget: "list"
            summary: "{{fields.title}}" 
            fields:
              - {label: "اسم المشروع بالإنجليزية", name: "title", widget: "string"}
              - {label: "الوصف بالعربية", name: "description", widget: "string"}
              - {label: "ألبوم صور المشروع", name: "images", widget: "list", field: {label: "الصورة", name: "image", widget: "image"}}
