backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "معرض المشاريع"
    folder: "/"
    extension: "json"
    create: true
    slug: "projects"
    fields:
      - {label: "قائمة المشاريع", name: "projects", widget: "list", fields: [
          {label: "اسم المشروع بالإنجليزية", name: "title", widget: "string"},
          {label: "الوصف بالعربية", name: "description", widget: "string"},
          {label: "ألبوم صور المشروع (يمكنك رفع أكثر من صورة)", name: "images", widget: "list", field: {label: "الصورة", name: "image", widget: "image"}}
        ]}